name: Tests

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1000000

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Run FedericoCarboni/setup-ffmpeg
        uses: ./
      - name: Run FedericoCarboni/setup-ffmpeg
        id: setup-ffmpeg
        uses: ./
      - run: ffmpeg -version
      - run: ffmpeg -i input.mp4 -r 30 -filter:v "setpts=1.0*PTS" output1.mp4
